# Generated by Django 4.0.4 on 2022-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idcomentarios', models.IntegerField(db_column='idComentarios', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.IntegerField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('direccion', models.IntegerField(blank=True, db_column='Direccion', null=True)),
                ('codigopostal', models.CharField(blank=True, db_column='CodigoPostal', max_length=45, null=True)),
                ('sitioweb', models.CharField(blank=True, db_column='SitioWeb', max_length=45, null=True)),
                ('nombrecontacto', models.CharField(blank=True, db_column='NombreContacto', max_length=45, null=True)),
                ('numerocontacto', models.CharField(blank=True, db_column='NumeroContacto', max_length=45, null=True)),
                ('nit', models.IntegerField(blank=True, db_column='Nit', null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadocliente',
            fields=[
                ('idestadocliente', models.IntegerField(db_column='idEstadoCliente', primary_key=True, serialize=False)),
                ('activo', models.CharField(blank=True, db_column='Activo', max_length=45, null=True)),
                ('inactivo', models.CharField(blank=True, db_column='Inactivo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'estadocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('ideventos', models.IntegerField(db_column='idEventos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('numerocontacto', models.IntegerField(blank=True, db_column='NumeroContacto', null=True)),
                ('horarioinicio', models.CharField(blank=True, db_column='HorarioInicio', max_length=45, null=True)),
                ('horariofinal', models.CharField(blank=True, db_column='HorarioFinal', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('sitioweb', models.CharField(blank=True, db_column='SitioWeb', max_length=45, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('tipoeventos_idtipoeventos', models.IntegerField(db_column='TipoEventos_idTipoEventos')),
                ('reservas_idreservas', models.IntegerField(db_column='Reservas_idReservas')),
                ('reservas_restaurantes_idrestaurante', models.IntegerField(db_column='Reservas_Restaurantes_idRestaurante')),
                ('reservas_restaurantes_tipolugar_idtipolugar', models.IntegerField(db_column='Reservas_Restaurantes_Tipolugar_idtipolugar')),
                ('ofertas_idofertas', models.IntegerField(db_column='Ofertas_idOfertas')),
                ('serviciotour_idserviciotour', models.IntegerField(db_column='ServicioTour_idServicioTour')),
                ('comentarios_idcomentarios', models.IntegerField(db_column='Comentarios_idComentarios')),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('idsitiosturisticos', models.IntegerField(db_column='idSitiosTuristicos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('horario', models.CharField(blank=True, db_column='Horario', max_length=45, null=True)),
                ('empresa_idempresa', models.IntegerField(db_column='Empresa_idEmpresa')),
                ('tipolugar_idtipolugar', models.IntegerField(db_column='Tipolugar_idtipolugar')),
                ('eventos_ideventos', models.IntegerField(db_column='Eventos_idEventos')),
            ],
            options={
                'db_table': 'lugar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idofertas', models.IntegerField(db_column='idOfertas', primary_key=True, serialize=False)),
                ('precios', models.CharField(blank=True, db_column='Precios', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('fechainicio', models.IntegerField(blank=True, db_column='FechaInicio', null=True)),
                ('fechafinal', models.IntegerField(blank=True, db_column='FechaFinal', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'ofertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('field_idcliente', models.IntegerField(db_column=' idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('identificacion', models.IntegerField(blank=True, db_column='Identificacion', null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('celular', models.IntegerField(blank=True, db_column='Celular', null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='FechaNacimiento', null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=45, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=45, null=True)),
                ('tipopersona_idtipocliente', models.IntegerField(db_column='TipoPersona_idTipoCliente')),
                ('empresa_idempresa', models.IntegerField(db_column='Empresa_idEmpresa')),
                ('tipodocumento_idtipodocumento', models.IntegerField(db_column='TipoDocumento_idTipoDocumento')),
                ('estadocliente_idestadocliente', models.IntegerField(db_column='EstadoCliente_idEstadoCliente')),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('idreservas', models.IntegerField(db_column='idReservas', primary_key=True, serialize=False)),
                ('estador', models.CharField(blank=True, db_column='EstadoR', max_length=45, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='FechaInicio', null=True)),
                ('fechafinal', models.DateField(blank=True, db_column='FechaFinal', null=True)),
                ('cliente', models.CharField(blank=True, db_column='Cliente', max_length=45, null=True)),
                ('comprobante', models.CharField(blank=True, db_column='Comprobante', max_length=45, null=True)),
                ('cupoadulto', models.IntegerField(blank=True, db_column='CupoAdulto', null=True)),
                ('cuponino', models.IntegerField(blank=True, db_column='CupoNino', null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('tiporeserva_idtiporeserva', models.IntegerField(db_column='TipoReserva_idTipoReserva')),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('idrutas', models.IntegerField(db_column='idRutas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviciotour',
            fields=[
                ('idserviciotour', models.IntegerField(db_column='idServicioTour', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('rutas_idrutas', models.IntegerField(db_column='Rutas_idRutas')),
            ],
            options={
                'db_table': 'serviciotour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.IntegerField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, db_column='Denominacion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoeventos',
            fields=[
                ('idtipoeventos', models.IntegerField(db_column='idTipoEventos', primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, db_column='Denominacion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipoeventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipolugar',
            fields=[
                ('idtipolugar', models.IntegerField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(blank=True, db_column='Denominacion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipolugar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporeserva',
            fields=[
                ('idtiporeserva', models.IntegerField(db_column='idTipoReserva', primary_key=True, serialize=False)),
                ('precio', models.CharField(blank=True, db_column='Precio', max_length=45, null=True)),
                ('actividades', models.CharField(blank=True, db_column='Actividades', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tiporeserva',
                'managed': False,
            },
        ),
    ]
